package com.blueskyminds.nonuselection.model;

import org.apache.commons.lang.ArrayUtils;

/**
 * Date Started: 19/10/2008
 * <p/>
 * Copyright (c) 2008 Blue Sky Minds Pty Ltd
 */
public class Countries {

    private static final String[] countyCodes = {
            "all",
            "al",
            "dz",
            "ar",
            "au",
            "at",
            "bh",
            "by",
            "be",
            "bo",
            "ba",
            "br",
            "bg",
            "ca",
            "cl",
            "cn",
            "co",
            "cr",
            "hr",
            "cz",
            "dk",
            "do",
            "ec",
            "eg",
            "sv",
            "ee",
            "fi",
            "fr",
            "de",
            "gr",
            "gt",
            "hn",
            "hk",
            "hu",
            "is",
            "in",
            "iq",
            "ie",
            "il",
            "it",
            "jp",
            "jo",
            "kw",
            "lv",
            "lb",
            "ly",
            "lt",
            "lu",
            "mk",
            "mx",
            "ma",
            "nl",
            "nz",
            "ni",
            "no",
            "om",
            "pa",
            "py",
            "pe",
            "pl",
            "pt",
            "pr",
            "qa",
            "ro",
            "ru",
            "sa",
            "cs",
            "sk",
            "si",
            "za",
            "kr",
            "es",
            "sd",
            "se",
            "ch",
            "sy",
            "tw",
            "th",
            "tn",
            "tr",
            "ua",
            "ae",
            "gb",
            "us",
            "uy",
            "ve",
            "vn",
            "ye"
    };

    public static boolean isValid(String country) {
        return ArrayUtils.contains(countyCodes, country);
    }
}
